version: '3'
services:
  apipython:
    image: apipython
    deploy:
      replicas: 1
    build:
      context:  ./app
      dockerfile:  Dockerfile
    stdin_open: true
    tty: true
    restart: on-failure:3
    ports:
      - "5000:5000"

      